import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { complianceService } from '../api/services/complianceService';

export interface ComplianceAlert {
  id: string;
  employerId: string;
  alertType: 'contract_expiry' | 'bpjs_overdue' | 'overtime_limit' | 'document_missing' | 'tax_deadline' | 'labor_law_violation';
  severity: 'critical' | 'warning' | 'info';
  title: string;
  message: string;
  relatedEntityId?: string;
  relatedEntityType?: string;
  dueDate?: string;
  resolvedAt?: string;
  resolvedBy?: string;
  autoGenerated: boolean;
  metadata?: Record<string, any>;
  createdAt: string;
}

export interface AuditLog {
  id: string;
  employerId: string;
  userId: string;
  userName: string;
  action: string;
  entityType: string;
  entityId: string;
  changes?: Record<string, any>;
  ipAddress?: string;
  userAgent?: string;
  createdAt: string;
}

export const complianceKeys = {
  all: ['compliance'] as const,
  alerts: () => [...complianceKeys.all, 'alerts'] as const,
  alertsList: (employerId: string, filters?: any) => [...complianceKeys.alerts(), employerId, filters] as const,
  auditLogs: () => [...complianceKeys.all, 'audit-logs'] as const,
  auditLogsList: (employerId: string, filters?: any) => [...complianceKeys.auditLogs(), employerId, filters] as const,
};

/**
 * Fetch compliance alerts
 */
export function useComplianceAlerts(
  employerId: string | null,
  filters?: { severity?: string; status?: string }
) {
  return useQuery({
    queryKey: complianceKeys.alertsList(employerId!, filters),
    queryFn: () => complianceService.getAlerts(employerId!, filters),
    enabled: !!employerId,
    refetchInterval: 60000, // Refetch every minute for critical alerts
  });
}

/**
 * Resolve compliance alert
 */
export function useResolveAlert() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ alertId, resolution }: { alertId: string; resolution?: string }) =>
      complianceService.resolveAlert(alertId, resolution),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: complianceKeys.alerts() });
      toast.success('Alert resolved successfully');
    },
    onError: (error: Error) => {
      toast.error('Failed to resolve alert', {
        description: error.message,
      });
    },
  });
}

/**
 * Fetch audit logs
 */
export function useAuditLogs(
  employerId: string | null,
  filters?: { action?: string; entityType?: string; startDate?: string; endDate?: string }
) {
  return useQuery({
    queryKey: complianceKeys.auditLogsList(employerId!, filters),
    queryFn: () => complianceService.getAuditLogs(employerId!, filters),
    enabled: !!employerId,
  });
}
