import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ComplianceDashboard } from '../ComplianceDashboard';

// Mock the hooks
vi.mock('@/lib/hooks/useAuth', () => ({
  useAuth: () => ({
    employerId: 'test-employer-123',
    employeeId: 'test-employee-456',
    user: { id: 'test-user', email: 'test@example.com', role: 'employer' },
    isAuthenticated: true,
    isLoading: false,
  }),
}));

vi.mock('@/lib/hooks/useCompliance', () => ({
  useComplianceAlerts: vi.fn(),
  useAuditLogs: vi.fn(),
  useResolveAlert: vi.fn(),
}));

import { useComplianceAlerts, useAuditLogs, useResolveAlert } from '@/lib/hooks/useCompliance';

describe('ComplianceDashboard', () => {
  let queryClient: QueryClient;

  beforeEach(() => {
    queryClient = new QueryClient({
      defaultOptions: {
        queries: { retry: false },
        mutations: { retry: false },
      },
    });

    vi.clearAllMocks();
  });

  const wrapper = ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  );

  it('should render loading state', () => {
    vi.mocked(useComplianceAlerts).mockReturnValue({
      data: undefined,
      isLoading: true,
      error: null,
    } as any);

    vi.mocked(useAuditLogs).mockReturnValue({
      data: undefined,
      isLoading: true,
      error: null,
    } as any);

    render(<ComplianceDashboard />, { wrapper });

    expect(screen.getByText(/loading compliance alerts/i)).toBeInTheDocument();
  });

  it('should display compliance alert summary cards', async () => {
    const mockData = {
      alerts: [
        {
          id: '1',
          severity: 'critical',
          title: 'Contract Expiring',
          message: 'Contract expiring soon',
          employerId: 'test-employer-123',
          alertType: 'contract_expiry',
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        },
        {
          id: '2',
          severity: 'warning',
          title: 'BPJS Overdue',
          message: 'BPJS registration needed',
          employerId: 'test-employer-123',
          alertType: 'bpjs_overdue',
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        },
      ],
      total: 2,
    };

    vi.mocked(useComplianceAlerts).mockReturnValue({
      data: mockData,
      isLoading: false,
      error: null,
    } as any);

    vi.mocked(useAuditLogs).mockReturnValue({
      data: { logs: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    render(<ComplianceDashboard />, { wrapper });

    await waitFor(() => {
      expect(screen.getByText('Critical Alerts')).toBeInTheDocument();
      expect(screen.getByText('Warnings')).toBeInTheDocument();
      expect(screen.getByText('Total Items')).toBeInTheDocument();
    });

    // Verify counts
    expect(screen.getByText('1')).toBeInTheDocument(); // 1 critical
    expect(screen.getByText('1')).toBeInTheDocument(); // 1 warning
    expect(screen.getByText('2')).toBeInTheDocument(); // 2 total
  });

  it('should display compliance alerts list', async () => {
    const mockData = {
      alerts: [
        {
          id: '1',
          severity: 'critical',
          title: 'Contract Expiring Soon',
          message: '3 employees have contracts expiring',
          employerId: 'test-employer-123',
          alertType: 'contract_expiry',
          autoGenerated: true,
          dueDate: '2024-12-15',
          createdAt: new Date().toISOString(),
        },
      ],
      total: 1,
    };

    vi.mocked(useComplianceAlerts).mockReturnValue({
      data: mockData,
      isLoading: false,
      error: null,
    } as any);

    vi.mocked(useAuditLogs).mockReturnValue({
      data: { logs: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    render(<ComplianceDashboard />, { wrapper });

    await waitFor(() => {
      expect(screen.getByText('Contract Expiring Soon')).toBeInTheDocument();
      expect(screen.getByText(/3 employees have contracts expiring/i)).toBeInTheDocument();
    });
  });

  it('should show empty state when no alerts', async () => {
    vi.mocked(useComplianceAlerts).mockReturnValue({
      data: { alerts: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    vi.mocked(useAuditLogs).mockReturnValue({
      data: { logs: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    render(<ComplianceDashboard />, { wrapper });

    await waitFor(() => {
      expect(screen.getByText(/no compliance alerts/i)).toBeInTheDocument();
      expect(screen.getByText(/all compliance checks passed/i)).toBeInTheDocument();
    });
  });

  it('should handle resolve alert click', async () => {
    const user = userEvent.setup();
    const mockResolve = vi.fn().mockResolvedValue({});

    const mockData = {
      alerts: [
        {
          id: 'alert-1',
          severity: 'warning',
          title: 'Test Alert',
          message: 'Test alert message',
          employerId: 'test-employer-123',
          alertType: 'bpjs_overdue',
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        },
      ],
      total: 1,
    };

    vi.mocked(useComplianceAlerts).mockReturnValue({
      data: mockData,
      isLoading: false,
      error: null,
    } as any);

    vi.mocked(useAuditLogs).mockReturnValue({
      data: { logs: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    vi.mocked(useResolveAlert).mockReturnValue({
      mutateAsync: mockResolve,
      isPending: false,
    } as any);

    render(<ComplianceDashboard />, { wrapper });

    await waitFor(() => {
      expect(screen.getByText('Test Alert')).toBeInTheDocument();
    });

    const resolveButton = screen.getByRole('button', { name: /resolve/i });
    await user.click(resolveButton);

    await waitFor(() => {
      expect(mockResolve).toHaveBeenCalledWith({ alertId: 'alert-1' });
    });
  });

  it('should display auto-refresh indicator', async () => {
    vi.mocked(useComplianceAlerts).mockReturnValue({
      data: { alerts: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    vi.mocked(useAuditLogs).mockReturnValue({
      data: { logs: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    render(<ComplianceDashboard />, { wrapper });

    await waitFor(() => {
      expect(screen.getByText(/auto-refreshes every minute/i)).toBeInTheDocument();
    });
  });

  it('should display audit logs', async () => {
    const mockAuditLogs = {
      logs: [
        {
          id: '1',
          employerId: 'test-employer-123',
          userId: 'user-1',
          userName: 'Admin User',
          action: 'Employee Created',
          entityType: 'employee',
          entityId: 'emp-1',
          createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
        },
        {
          id: '2',
          employerId: 'test-employer-123',
          userId: 'user-2',
          userName: 'HR Manager',
          action: 'Payroll Approved',
          entityType: 'payroll',
          entityId: 'payroll-1',
          createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), // 5 hours ago
        },
      ],
      total: 2,
    };

    vi.mocked(useComplianceAlerts).mockReturnValue({
      data: { alerts: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    vi.mocked(useAuditLogs).mockReturnValue({
      data: mockAuditLogs,
      isLoading: false,
      error: null,
    } as any);

    render(<ComplianceDashboard />, { wrapper });

    await waitFor(() => {
      expect(screen.getByText('Recent Audit Log')).toBeInTheDocument();
      expect(screen.getByText('Employee Created')).toBeInTheDocument();
      expect(screen.getByText('Payroll Approved')).toBeInTheDocument();
      expect(screen.getByText(/by Admin User/i)).toBeInTheDocument();
      expect(screen.getByText(/by HR Manager/i)).toBeInTheDocument();
    });
  });

  it('should show due dates for alerts', async () => {
    const mockData = {
      alerts: [
        {
          id: '1',
          severity: 'critical',
          title: 'Contract Expiring',
          message: 'Contract expires soon',
          employerId: 'test-employer-123',
          alertType: 'contract_expiry',
          autoGenerated: true,
          dueDate: '2024-12-15',
          createdAt: new Date().toISOString(),
        },
      ],
      total: 1,
    };

    vi.mocked(useComplianceAlerts).mockReturnValue({
      data: mockData,
      isLoading: false,
      error: null,
    } as any);

    vi.mocked(useAuditLogs).mockReturnValue({
      data: { logs: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    render(<ComplianceDashboard />, { wrapper });

    await waitFor(() => {
      expect(screen.getByText(/Due:/i)).toBeInTheDocument();
    });
  });

  it('should show auto-generated badge', async () => {
    const mockData = {
      alerts: [
        {
          id: '1',
          severity: 'warning',
          title: 'Auto Alert',
          message: 'Auto generated alert',
          employerId: 'test-employer-123',
          alertType: 'document_missing',
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        },
      ],
      total: 1,
    };

    vi.mocked(useComplianceAlerts).mockReturnValue({
      data: mockData,
      isLoading: false,
      error: null,
    } as any);

    vi.mocked(useAuditLogs).mockReturnValue({
      data: { logs: [], total: 0 },
      isLoading: false,
      error: null,
    } as any);

    render(<ComplianceDashboard />, { wrapper });

    await waitFor(() => {
      expect(screen.getByText(/auto-generated/i)).toBeInTheDocument();
    });
  });
});
